data_params:
  batch_size: 32
  num_workers: 8
  augmentation_params:
    resize: 224

train_params:
  name: rn34-shot_type_2
  model: models.Net34
  model_params:
    pretrained: True
    num_classes: 4
  loss: losses.CrossEntropyLoss
  loss_params: {}
  metrics: [metrics.Accuracy]
  steps_per_epoch: 2500
  new_save: True
#  weights: /mnt/hdd2/datasets/naive_data/shot_dataset/weights/weights/rn34-shot_type-wedding_dataset/0/tt_1_0.79849.pt
stages:
-
  load_best: False
  optimizer: Adam
  optimizer_params:
    lr: 0.0001
  scheduler: ReduceLROnPlateau
  scheduler_params:
    patience: 5
    factor: 0.1
    min_lr: 0.0000001
    verbose: True
  epochs: 300
  augmentation: mix_transform
#-
#  load_best: False
#  optimizer: Adam
#  optimizer_params:
#    lr: 0.0001
#  scheduler: schedulers.Cycle_LR
#  scheduler_params:
#    optimizer: Adam
#    lr_factor: 0.1
#    cycle_len: 5
#    cycle_factor: 2
#    gamma: None
#    jump: None
#    last_epoch: -1
#    surface: None
#    momentum_range: None
##    patience: 5
##    factor: 0.5
##    min_lr: 0.0000001
##    verbose: True
#  epochs: 300
#  augmentation: mix_transform2
