data_params:
  batch_size: 32
  num_workers: 12
  augmentation_params:
    resize: 224

train_params:
  name: se_rn34-shot_type_2
  model: models.SE_Resnet34_Shot
  model_params:
    pretrained: True
    num_classes: 4
  loss: losses.MixupCrossEntropyLoss
  loss_params: {}
  metrics: [metrics.Accuracy]
  steps_per_epoch: 5000
  new_save: True
#  weights: /home/kg2/se_resnet34_best.pth

stages:
-
  load_best: False
#  optimizer: SGD
  optimizer: Adam
  optimizer_params:
    lr: 0.001  # 0.00001 for regular models and 0.001 for se_pd
  scheduler: ReduceLROnPlateau
  scheduler_params:
    patience: 3
    factor: 0.5
    min_lr: 0.0000001
    verbose: True
  epochs: 100
  augmentation: mix_transform
#-
#  load_best: False
#  optimizer: Adam
#  optimizer_params:
#    lr: 0.00001
#  scheduler: Cycle_LR
#  scheduler_params:
#    optimizer: Adam
#    lr_factor: 10
#    cycle_len: 10
#    gamma: 0.8
#  epochs: 300
#  augmentation: mix_transform2
