#dumps:
#  path: /mnt/hdd1/datasets/naive_data/shot_dataset/weights/   # path to weights dir
#  weights: weights                  # name of weights dir
#  logs: logs                        # name of logs dir
#  name_save: tt                     # name to save models
#
#data:
#  path: /mnt/hdd1/datasets/naive_data/shot_dataset/  # path to data directory
#  train_images: train/   # dir to train images
#  train_masks: gt/    # dir to labels
#  test_images: test/  # dir to test
#  folds: folds.csv                  # validation folds
#  predictions_path: preds.csv       # predictions name


dumps:
  path: /mnt/hdd2/datasets/naive_data/shot_dataset/weights/    # path to weights dir
  weights: weights                  # name of weights dir
  code: code
  logs: logs                        # name of logs dir
  name_save: tt                     # name to save models

data:
  path: /mnt/hdd2/datasets/naive_data/shot_dataset/shot_total_bigger/  # path to data directory
  train_images: train/   # dir to train images
#  train_masks: gt/    # dir to labels
  test_images: testset/  # dir to test
  folds: folds.csv                  # validation folds
  predictions_path: preds.csv       # predictions name
