dumps:
  path: /mnt/hdd2/datasets/naive_data/shot_dataset/weights/ #kg2
  weights: weights
  code: code
  logs: logs
  name_save: rn

data:
  path: /mnt/hdd2/datasets/naive_data/shot_dataset/shot_total_bigger/  # kg2
  train_images: train/   # dir to train images
#  train_masks: gt/    # dir to labels
  val_images: val/
  test_images: testset/  # dir to test
  folds: folds.csv                  # validation folds
  predictions_path: preds.csv       # predictions name
