dumps:
  path: /mnt/hdd2/datasets/naive_data/shot_dataset/weights/    # path to weights dir
  weights: weights                  # name of weights dir
  code: code                        # name of code dir
  logs: logs                        # name of logs dir
  name_save: tt                     # name to save models

data:
  path: /mnt/hdd2/datasets/naive_data/shot_dataset/shot_total_bigger/  # path to data directory
  train_images: fixed_train/   # dir to train images
  val_images: val/
  test_images: testset/  # dir to test
  folds: fixed_folds.csv
  predictions_path: preds.csv       # predictions name
